global:
# scrape_interval: 15s

scrape_configs:
- job_name: 'node_exporter'
  static_configs:
  - targets: ['freepbx:9100']

- job_name: 'asterisk_exporter'
  static_configs:
  - targets: ['freepbx:9487']
